### ISSUE TITLE
Examples not woking

### ISSUE THREAD

**Issue by sismasamuel** [atmtools/arts-lectures#87]
I installed ATRS and Testexample .py worked. But when I tried to run absorption.ipynb its showing like this 

--------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
/tmp/ipykernel_12347/2548510084.py in <module>
      5 
      6 # Call ARTS to calculate absorption cross sections
----> 7 freq, abs_xsec = calculate_absxsec(species, pressure, temperature)

~/arts-2.4.0/controlfiles-python/example/01-rotational_spectra/absorption_module.py in calculate_absxsec(species, pressure, temperature, fmin, fmax, fnum, lineshape, normalization, verbosity)
     59 
     60     ws.abs_lines_per_speciesReadSpeciesSplitCatalog(
---> 61        basename="spectroscopy/Artscat/"
     62     )
     63 

~/arts-2.4.0/build/python/pyarts/workspace/workspace.py in __call__(self, *args, **kwargs)
    269 
    270     def __call__(self, *args, **kwargs):
--> 271         self.m.call(self.ws, *args, **kwargs)
    272 
    273     def __repr__(self):

~/arts-2.4.0/build/python/pyarts/workspace/methods.py in call(*args, **kwargs)
    456         if (e_ptr):
    457             raise Exception("Call to ARTS WSM " + self.name + " failed with error: "
--> 458                            + e_ptr.decode("utf8").format())
    459 
    460         # Remove temporaries from workspace (in reverse order).

Exception: Call to ARTS WSM abs_lines_per_speciesReadSpeciesSplitCatalog failed with error: Cannot find any bands in the directory you are reading

**Comment by olemke** [comment]
The current version of the arts-lectures requires ARTS 2.5.8. You can either follow the instructions in the README to install the pre-compiled conda package of PyARTS or download the ARTS source code from the [ARTS releases page](https://github.com/atmtools/arts/releases).
