### ISSUE TITLE
attribute error while exexcuting  Exercise 5: Jacobian and opacity rule

### ISSUE THREAD

**Issue by sismasamuel** [atmtools/arts-lectures#88]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_75718/1219081892.py in <cell line: 3>()
      1 # Calculate Jacobians (ARTS)
      2 jacobian_quantity = "H2O"
----> 3 calc_jacobians(jacobian_quantity=jacobian_quantity)
      4 
      5 # read in everything

~/arts-lectures-master/exercises/05-jacobian/jacobian_module.py in calc_jacobians(jacobian_quantity, fmin, fmax, fnum, verbosity)
    137     """Calculate jacobians for a given species and frequency range."""
    138     ws = pyarts.workspace.Workspace(verbosity=0)
--> 139     ws.water_p_eq_agendaSet()
    140     ws.PlanetSet(option="Earth")
    141     ws.verbositySetScreen(ws.verbosity, verbosity)

~/.local/lib/python3.10/site-packages/pyarts/workspace/workspace.py in __getattr__(self, name)
    479             i = arts_api.lookup_workspace_variable(name.encode())
    480             if i < 0:
--> 481                 raise AttributeError("No workspace variable " + str(name) + " found.")
    482             vs = arts_api.get_variable(i)
    483             group_id    = vs.group

AttributeError: No workspace variable water_p_eq_agendaSet found.

**Comment by sismasamuel** [comment]
I retried with pyarts2.5.8.

but results files are not written when jacobian _module.py is executed. 

RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_6427/1219081892.py in <cell line: 3>()
      1 # Calculate Jacobians (ARTS)
      2 jacobian_quantity = "H2O"
----> 3 calc_jacobians(jacobian_quantity=jacobian_quantity)
      4 
      5 # read in everything

~/arts-lectures-master/exercises/05-jacobian/jacobian_module.py in calc_jacobians(jacobian_quantity, fmin, fmax, fnum, verbosity)
    187 
    188     # Read a line file and a matching small frequency grid
--> 189     ws.abs_lines_per_speciesReadSpeciesSplitCatalog(basename="lines/")
    190 
    191     ws.abs_lines_per_speciesCutoff(option="ByLine", value=750e9)

RuntimeError: User Error: not bands_found and not robust
Error is found at:
	/home/nizy/arts-2.5.8/src/m_absorptionlines.cc:918
Please follow these instructions to correct your error:
Cannot find any bands in the directory you are reading

**Comment by olemke** [comment]
Your path to the catalog is wrong. `abs_lines_per_speciesReadSpeciesSplitCatalog` expects the path to the directory of the catalog, but you're specifying the path to an xml file. I also think that you're missing a leading '/' in your path. It should look like this:
```
ws.abs_lines_per_speciesReadSpeciesSplitCatalog(basename="/home/nizy/arts-cat-data-snapshot-arts-2.5.8/lines/")
```
Which files are read from the catalog is determined by the species names set in `abs_species`.

**Comment by vibinj** [comment]
I tried but still some error . kindly help


RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_16784/1219081892.py in <cell line: 3>()
      1 # Calculate Jacobians (ARTS)
      2 jacobian_quantity = "H2O"
----> 3 calc_jacobians(jacobian_quantity=jacobian_quantity)
      4
      5 # read in everything

~/arts-lectures-master/exercises/05-jacobian/jacobian_module.py in calc_jacobians(jacobian_quantity, fmin, fmax, fnum, verbosity)
    187
    188     # Read a line file and a matching small frequency grid
--> 189     ws.abs_lines_per_speciesReadSpeciesSplitCatalog(basename="/home/nizy/arts-cat-data-snapshot-arts-2.5.8/lines/")
    190
    191     ws.abs_lines_per_speciesCutoff(option="ByLine", value=750e9)

RuntimeError: User Error: not bands_found and not robust
Error is found at:
/home/nizy/arts-2.5.8/src/m_absorptionlines.cc:918
Please follow these instructions to correct your error:
Cannot find any bands in the directory you are reading

**Comment by sismasamuel** [comment]
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_398851/2623034860.py in <cell line: 3>()
      1 # Calculate Jacobians (ARTS)
      2 jacobian_quantity = "H2O"
----> 3 calc_jacobians(jacobian_quantity=jacobian_quantity)
      4 
      5 # read in everything

~/arts-lectures-master/exercises/05-jacobian/jacobian_module.py in calc_jacobians(jacobian_quantity, fmin, fmax, fnum, verbosity)
    138     ws = pyarts.workspace.Workspace(verbosity=1)
    139     ws.water_p_eq_agendaSet()
--> 140     ws.PlanetSet(option="/home/nizy/arts-xml-data-snapshot-arts-2.5.8/planets/Earth/ECMWF/ERA40/")
    141     ws.verbositySetScreen(ws.verbosity, verbosity)
    142 

**RuntimeError: User Error: not good_enum(type)
Error is found at:
	/home/nizy/arts-2.5.8/src/enums.h:91
Please follow these instructions to correct your error:
Cannot understand argument: "/home/nizy/arts-xml-data-snapshot-arts-2.5.8/planets/Earth"
Valid planetDefaultOptions options are: [Earth, Io, Jupiter, Mars, Venus]**

**Comment by olemke** [comment]
The `option` argument in `PlanetSet` doesn't take a path. As the error message says: `Valid planetDefaultOptions options are: [Earth, Io, Jupiter, Mars, Venus]`. Leave the original value "Earth" there.
