### ISSUE TITLE
AttributeError: No workspace variable water_p_eq_agendaSet found.

### ISSUE THREAD

**Issue by vibinj** [atmtools/arts-lectures#89]
I installed arts 2.5.8, and I tried to run the examples given. but for all the examples, I am getting an attribute error. How to check

**Comment by olemke** [comment]
`water_p_eq_agendaSet` being undefined indicates that you're not using pyarts 2.5.8. You can check your pyarts version by running `python -c 'import pyarts;print(pyarts.__version__)'`.
If you installed the pyarts 2.5.8 conda package, you might still have an older version manually installed in `~/.local` that takes precedence over the conda package.

**Comment by vibinj** [comment]
not able to rum the jacobian for any species or channels


RuntimeError                              Traceback (most recent call last)
/tmp/ipykernel_16784/1219081892.py in <cell line: 3>()
      1 # Calculate Jacobians (ARTS)
      2 jacobian_quantity = "H2O"
----> 3 calc_jacobians(jacobian_quantity=jacobian_quantity)
      4
      5 # read in everything

~/arts-lectures-master/exercises/05-jacobian/jacobian_module.py in calc_jacobians(jacobian_quantity, fmin, fmax, fnum, verbosity)
    187
    188     # Read a line file and a matching small frequency grid
--> 189     ws.abs_lines_per_speciesReadSpeciesSplitCatalog(basename="/media/vib/arts-cat-data-snapshot-arts-2.5.8/lines/")
    190
    191     ws.abs_lines_per_speciesCutoff(option="ByLine", value=750e9)

RuntimeError: User Error: not bands_found and not robust
Error is found at:
/media/vib/arts-2.5.8/src/m_absorptionlines.cc:918
Please follow these instructions to correct your error:
Cannot find any bands in the directory you are reading

**Comment by olemke** [comment]
This indicates that the catalog directory cannot be found. Double-check that the location is correct. If you run `ls /media/vib/arts-cat-data-snapshot-arts-2.5.8/lines/` in a terminal, does it find the directory and displays the list of xml catalog files?
